### PR TITLE
Change Lists docs 7.2

### PR DESCRIPTION
**Pull request by codyhoag**
Hey Dave; can you please review these Change List docs for accuracy. They've been reviewed and approved by @danielkocsis, but we wanted to get your approval as well. Also, let me know if there's any other info I missed that should be covered for the initial release.

There are currently six articles:

- Intro
- Enabling Change Lists
- Creating Change Lists
- Managing Change Lists
- Editing Multiple Change Lists in Parallel
- Configuring Permissions for Change Lists

Thanks!

### CODE REVIEW

**Comment by codyhoag** [comment]
@david-truong I'll need this reviewed before Monday morning if we want this to make the docs launch for 7.2. Do you have time to get to this before then? Thanks!

**Comment by david-truong** [comment]
I've started but haven't finished yet

**Comment by david-truong** [comment]
Just started reviewing :)

**Comment by david-truong** [comment]
Pull request submitted to https://github.com/codyhoag/liferay-docs/pull/158. [See changes here.](https://github.com/david-truong/liferay-docs/compare/f4bb99ec5~1...f4bb99ec5)

**Pull request closed without merging**
